version: '3'
services:
  jupyter:
    image: jupyter/datascience-notebook:r-4.3.1
    container_name: westac_statistics
    environment:
      - JUPYTER_TOKEN=westac_tomas_pass_letsgo
    volumes:
      - ./mounts:/home/jovyan/work
      - ./scripts:/home/jovyan/scripts
      - ./py_notebooks:/home/jovyan/py_notebooks
      - ./reference_files:/home/jovyan/work/reference_files
      - ../westac_statistics:/home/jovyan/work/westac_statistics
      - ../riksdagen-corpus/:/home/jovyan/work/riksdagen-corpus
    command: >
      bash -c "set -e &&
               pip install jupytext &&
               pushd /home/jovyan/scripts &&
               chmod +x ./py_to_notebook.sh &&
               chmod +x ./notebook_to_py.sh &&
               ./py_to_notebook.sh &&
               popd &&
               start-notebook.sh"
    ports:
      - 9006:8888
    networks:
      westac-network:
        ipv4_address: 10.125.0.5

networks:
  westac-network:
    ipam:
      driver: default
      config:
        - subnet: 10.125.0.0/16
